---
apiVersion: v1
kind: Service
metadata:
  name: sdjpa-order-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sdjpa-order-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdjpa-order-service
  labels:
    app: sdjpa-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdjpa-order-service
  template:
    metadata:
      labels:
        app: sdjpa-order-service
    spec:
      containers:
        - name: sdjpa-order-service
          image: domboeckli/sdjpa-order-service:0.0.1-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/orderservicedb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6